-- Generated by tools/build_bag_catalog.py; saved model IDs never change.
local V=VanityStudio
V.bagCatalog={
    {id=1,name="Runecloth Bag",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon1.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\DarkSchoolbag.mdx"},
    {id=2,name="Amber Traveler Even Strap",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon2.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\AmberTravelerEvenStrap.mdx"},
    {id=5,name="Milloo No Zippers",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon5.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\MillooNoZippers.mdx"},
    {id=7,name="Milloo Smooth Dark Leather",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon7.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothDarkLeather.mdx"},
    {id=8,name="Milloo Smooth Tan Leather",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon8.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothTanLeather.mdx"},
    {id=10,name="Ranger Rucksack",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon10.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\RangerRucksack.mdx"},
    {id=11,name="Black Leather Sling",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon11.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\BlackLeatherSling.mdx"},
    {id=12,name="Burgundy Cloth Pouch Low",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon12.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\BurgundyClothPouchLow.mdx"},
    {id=13,name="Navy Cloth Pouch Low",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon13.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\NavyClothPouchLow.mdx"},
    {id=14,name="Ochre Cloth Pouch Low",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon14.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\OchreClothPouchLow.mdx"},
    {id=16,name="Olive Cloth Pouch Low",icon="Interface\\AddOns\\SaureksCloset\\Textures\\BagIcon16.tga",model="Interface\\AddOns\\SaureksCloset\\Models\\OliveClothPouchLow.mdx"},
}
V.bagCatalogByID={}
for _,bag in ipairs(V.bagCatalog) do V.bagCatalogByID[bag.id]=bag end
-- Model choices group matching geometry while saved looks retain asset IDs.
V.bagModelChoices={
    V.bagCatalogByID[1],
    V.bagCatalogByID[2],
    V.bagCatalogByID[5],
    V.bagCatalogByID[7],
    V.bagCatalogByID[8],
    V.bagCatalogByID[10],
    V.bagCatalogByID[11],
    {id=16,name="Cloth Pouch",icon=V.bagCatalogByID[16].icon,colors={
        {id=12,name="Burgundy",r=0.48,g=0.18,b=0.22},
        {id=13,name="Navy",r=0.18,g=0.28,b=0.43},
        {id=14,name="Ochre",r=0.67,g=0.46,b=0.2},
        {id=16,name="Olive",r=0.39,g=0.43,b=0.22},
    }},
}
V.bagModelChoicesByID={}
V.bagModelColorsByID={}
for _,choice in ipairs(V.bagModelChoices) do
    V.bagModelChoicesByID[choice.id]=choice
    for _,color in ipairs(choice.colors or {}) do
        V.bagModelChoicesByID[color.id]=choice;V.bagModelColorsByID[color.id]=color
    end
end
-- Retired selections are removed (0) or migrated to an active model.
V.retiredBagModels={
    [3]=0,
    [4]=0,
    [6]=0,
    [9]=0,
    [15]=16,
}
