#pragma once
// Generated by tools/build_bag_catalog.py. IDs are stable across releases.
struct BagAsset { unsigned id; const char* name; const char* model; const char* texture; const char* material; };
static constexpr BagAsset bagCatalog[]={
    {1,"Runecloth Bag","Interface\\AddOns\\SaureksCloset\\Models\\DarkSchoolbag.mdx","Interface\\AddOns\\SaureksCloset\\Models\\DarkSchoolbag.blp","cloth"},
    {2,"Amber Traveler Even Strap","Interface\\AddOns\\SaureksCloset\\Models\\AmberTravelerEvenStrap.mdx","Interface\\AddOns\\SaureksCloset\\Models\\AmberTravelerEvenStrap.blp","canvas"},
    {3,"Burgundy Rucksack","Interface\\AddOns\\SaureksCloset\\Models\\BurgundyRucksack.mdx","Interface\\AddOns\\SaureksCloset\\Models\\BurgundyRucksack.blp","canvas"},
    {4,"Milloo Dark Leather","Interface\\AddOns\\SaureksCloset\\Models\\MillooDarkLeather.mdx","Interface\\AddOns\\SaureksCloset\\Models\\MillooDarkLeather.blp","leather"},
    {5,"Slim Leather Bag (Brown)","Interface\\AddOns\\SaureksCloset\\Models\\MillooNoZippers.mdx","Interface\\AddOns\\SaureksCloset\\Models\\MillooNoZippers.blp","leather"},
    {6,"Milloo Scratch","Interface\\AddOns\\SaureksCloset\\Models\\MillooScratch.mdx","Interface\\AddOns\\SaureksCloset\\Models\\MillooScratch.blp","leather"},
    {7,"Slim Leather Bag (Dark Brown)","Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothDarkLeather.mdx","Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothDarkLeather.blp","leather"},
    {8,"Slim Leather Bag (Tan)","Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothTanLeather.mdx","Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothTanLeather.blp","leather"},
    {9,"Milloo Tan Leather","Interface\\AddOns\\SaureksCloset\\Models\\MillooTanLeather.mdx","Interface\\AddOns\\SaureksCloset\\Models\\MillooTanLeather.blp","leather"},
    {10,"Ranger Rucksack","Interface\\AddOns\\SaureksCloset\\Models\\RangerRucksack.mdx","Interface\\AddOns\\SaureksCloset\\Models\\RangerRucksack.blp","canvas"},
    {11,"Black Leather Sling","Interface\\AddOns\\SaureksCloset\\Models\\BlackLeatherSling.mdx","Interface\\AddOns\\SaureksCloset\\Models\\BlackLeatherSling.blp","leather"},
    {12,"Mageweave Bag (Burgundy)","Interface\\AddOns\\SaureksCloset\\Models\\BurgundyClothPouchLow.mdx","Interface\\AddOns\\SaureksCloset\\Models\\BurgundyClothPouchLow.blp","cloth"},
    {13,"Mageweave Bag (Navy)","Interface\\AddOns\\SaureksCloset\\Models\\NavyClothPouchLow.mdx","Interface\\AddOns\\SaureksCloset\\Models\\NavyClothPouchLow.blp","cloth"},
    {14,"Mageweave Bag (Ochre)","Interface\\AddOns\\SaureksCloset\\Models\\OchreClothPouchLow.mdx","Interface\\AddOns\\SaureksCloset\\Models\\OchreClothPouchLow.blp","cloth"},
    {15,"Olive Cloth Pouch","Interface\\AddOns\\SaureksCloset\\Models\\OliveClothPouch.mdx","Interface\\AddOns\\SaureksCloset\\Models\\OliveClothPouch.blp","cloth"},
    {16,"Mageweave Bag (Olive)","Interface\\AddOns\\SaureksCloset\\Models\\OliveClothPouchLow.mdx","Interface\\AddOns\\SaureksCloset\\Models\\OliveClothPouchLow.blp","cloth"},
};
static constexpr unsigned bagCatalogCount=sizeof(bagCatalog)/sizeof(bagCatalog[0]);
static inline const BagAsset* bagAsset(unsigned id){
    for(const auto& asset:bagCatalog)if(asset.id==id)return &asset;
    return nullptr;
}
static inline const BagAsset* bagCatalogFind(unsigned id){return bagAsset(id);}
// Exact on-disk names: the client changes model .mdx requests to .m2.
static constexpr const char* bagAssetFiles[]={
    "Interface\\AddOns\\SaureksCloset\\Models\\DarkSchoolbag.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\DarkSchoolbag.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\AmberTravelerEvenStrap.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\AmberTravelerEvenStrap.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\BurgundyRucksack.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\BurgundyRucksack.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooDarkLeather.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooDarkLeather.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooNoZippers.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooNoZippers.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooScratch.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooScratch.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothDarkLeather.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothDarkLeather.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothTanLeather.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooSmoothTanLeather.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooTanLeather.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\MillooTanLeather.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\RangerRucksack.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\RangerRucksack.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\BlackLeatherSling.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\BlackLeatherSling.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\BurgundyClothPouchLow.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\BurgundyClothPouchLow.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\NavyClothPouchLow.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\NavyClothPouchLow.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\OchreClothPouchLow.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\OchreClothPouchLow.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\OliveClothPouch.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\OliveClothPouch.blp",
    "Interface\\AddOns\\SaureksCloset\\Models\\OliveClothPouchLow.m2",
    "Interface\\AddOns\\SaureksCloset\\Models\\OliveClothPouchLow.blp",
};
